apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-db-copy
spec:
  storageClassName: cstor-csi-disk
  dataSource:
    name: client-db-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi