apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: badri
  namespace: project-x
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: badri.dilbert@gmail.com
  namespace: default
